auto: true
server: true
markdown: rdiscount
pygments: true
exclude: ['README.md', 'src/', 'node_modules', 'package.json', 'Gruntfile.js', '*.command']
permalink: /:year/:month/:title
paginate: 5
paginate_path: "/page:num"
